#!/bin/sh -e

pkgname="ndoutils-2.0.0"

echo "UPGRADING NDOUTILS..."

# Delete the old directory
rm -rf "$pkgname"

# Extract archive
tar -xzf "$pkgname.tar.gz"

# Apply our patches
./apply-patches "$pkgname"

# Make and install NDOUtils
(
	cd "./$pkgname"
	./configure
	make
	make install-init
	# Copy 4.x module
	cp -f src/ndomod-4x.o /usr/local/nagios/bin/ndomod.o
    # Copy 4.x daemon
    cp -f src/ndo2db-4x /usr/local/nagios/bin/ndo2db
    # Copy utilities
    cp -f src/file2sock /usr/local/nagios/bin/
    cp -f src/log2ndo /usr/local/nagios/bin/
    cp -f src/sockdebug /usr/local/nagios/bin/
)

# Post-upgrade stuff
./post-upgrade "$pkgname"

# Delete the directory (source files not needed anymore)
rm -rf "$pkgname"

echo "NDOUTILS UPGRADED!"

